[package]
name = "geo-tools"
rust-version = "1.71"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.3.19", features = ["derive"] }
gdal = { version = "0.15.0", features = ["array"] }
gdal-sys = "0.9.0"
ndarray = "0.15.6"

[profile.release]
debug = true
