[package]
name = "erdy"
rust-version = "1.71"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
ball-tree = "0.4.0"
clap = { version = "4.4", features = ["derive"] }
# gdal = { version = "0.16", features = ["array"] }
# gdal-sys = "0.9"
gdal = { version = "0.16", git = "https://github.com/georust/gdal", features = ["array"] }
gdal-sys = { version = "0.9", git = "https://github.com/georust/gdal" }
indicatif = "0.17.7"
ndarray = "0.15"
num-traits = "0.2.17"
rand = { version = "0.8.5", features = ["small_rng"] }
tempfile = "3.8.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
walkdir = "2.4.0"

[profile.release]
debug = 2
