FROM ghcr.io/osgeo/gdal:ubuntu-full-3.9.3
RUN apt-get update
RUN apt-get install -y --no-install-recommends gcc libc-dev pkg-config
RUN --mount=type=cache,target=/root/.cargo \
    --mount=type=cache,target=/root/.rustup \
    curl --tlsv1.2 -fsS "https://sh.rustup.rs" | sh -s -- --default-toolchain nightly --profile minimal -y

WORKDIR /app
COPY Cargo.toml Cargo.lock .
COPY src src

RUN --mount=type=cache,target=/root/.cargo \
    --mount=type=cache,target=/root/.rustup \
    --mount=type=cache,target=/app/target/release/build \
    --mount=type=cache,target=/app/target/release/deps \
    --mount=type=cache,target=/app/target/release/.fingerprint \
    ~/.cargo/bin/cargo build --release

FROM ghcr.io/osgeo/gdal:ubuntu-full-3.9.3
COPY --from=0 /app/target/release/erdy /usr/local/bin/
