FROM ghcr.io/osgeo/gdal:ubuntu-full-3.9.2
RUN apt-get update -y
RUN apt-get install -y binutils curl pkg-config gcc
WORKDIR /app
RUN --mount=type=cache,target=/root/.cargo \
    --mount=type=cache,target=/root/.rustup \
    curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --profile minimal --default-toolchain stable --component rust-src -y
RUN --mount=type=cache,target=/root/.cargo \
    --mount=type=cache,target=/root/.rustup \
    --mount=type=cache,target=/app/target/release/build \
    --mount=type=cache,target=/app/target/release/deps \
    --mount=type=cache,target=/app/target/release/.fingerprint \
    --mount=type=bind,source=Cargo.toml,target=/app/Cargo.toml \
    --mount=type=bind,source=Cargo.lock,target=/app/Cargo.lock \
    --mount=type=bind,source=src,target=/app/src \
    ~/.cargo/bin/cargo build --release

FROM ghcr.io/osgeo/gdal:ubuntu-full-3.9.2
COPY --from=0 /app/target/release/erdy /usr/local/bin/
